import * as Assert from 'node:assert/strict'
import * as Fs from 'node:fs'
import * as Os from 'node:os'
import * as Path from 'node:path'
import test from 'node:test'
import {
  AssertBuildTagMatchesRevision,
  AssertReleaseEventAllowed,
  BuildImageReleasePlan,
  ParseReleaseRef,
  ParseReleaseTag
} from '../sources/docker_image_release.js'
import { RunVersioning } from '../sources/versioning.js'

const PackageName = 'sendmail-sec'

/* eslint-disable @typescript-eslint/naming-convention -- Test fixtures mirror repository and release metadata keys. */
type Workspace = {
  root: string
  manifestPath: string
  lockfilePath: string
}

type ReleasePlanSummary = {
  image: string
  tag: string
  kind: string
}
/* eslint-enable @typescript-eslint/naming-convention */

function CreateWorkspace(ManifestVersion = '0.1.0', LockVersion = '0.1.0'): Workspace {
  const Root = Fs.mkdtempSync(Path.join(Os.tmpdir(), 'sendmail-sec-versioning-'))
  const ManifestPath = Path.join(Root, 'Cargo.toml')
  const LockfilePath = Path.join(Root, 'Cargo.lock')

  Fs.writeFileSync(
    ManifestPath,
    `[package]
name = "${PackageName}"
version = "${ManifestVersion}"
edition = "2024"

[[bin]]
name = "${PackageName}"
path = "sources/main.rs"

[dependencies]
serde = "1.0.228"
`
  )

  Fs.writeFileSync(
    LockfilePath,
    `# This file is automatically @generated by Cargo.
version = 4

[[package]]
name = "${PackageName}"
version = "${LockVersion}"
dependencies = [
 "serde",
]

[[package]]
name = "serde"
version = "1.0.228"
source = "registry+https://github.com/rust-lang/crates.io-index"
checksum = "placeholder"
`
  )

  return { root: Root, manifestPath: ManifestPath, lockfilePath: LockfilePath }
}

function Cleanup(WorkspaceValue: Workspace): void {
  Fs.rmSync(WorkspaceValue.root, { force: true, recursive: true })
}

test('strict release tag parser accepts stable, beta, and build tags', () => {
  Assert.deepEqual(ParseReleaseTag('2.1.0'), {
    tag: '2.1.0',
    major: '2',
    minor: '1',
    patch: '0',
    kind: 'stable'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-beta.4'), {
    tag: '1.5.0-beta.4',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'beta',
    betaNumber: '4'
  })
  Assert.deepEqual(ParseReleaseTag('1.5.0-build.4f43abcd'), {
    tag: '1.5.0-build.4f43abcd',
    major: '1',
    minor: '5',
    patch: '0',
    kind: 'build',
    buildCommitPrefix: '4f43abcd'
  })
})

test('strict release tag parser rejects v prefixes and unsupported semver shapes', () => {
  for (const Tag of [
    'v1.2.3',
    '01.2.3',
    '1.02.3',
    '1.2.03',
    '1.2.3+build.4',
    '1.2.3-alpha.1',
    '1.2.3-beta.01',
    '1.2.3-build.4f43abc',
    '1.2.3-build.4f43abcg',
    '1.2'
  ]) {
    Assert.throws(() => ParseReleaseTag(Tag), /release tag/)
  }
})

test('release refs must be tag refs without v prefixes', () => {
  Assert.equal(ParseReleaseRef('refs/tags/1.2.3').tag, '1.2.3')
  Assert.throws(() => ParseReleaseRef('refs/heads/main'), /refs\/tags/)
  Assert.throws(() => ParseReleaseRef('refs/tags/v1.2.3'), /leading v/)
})

test('build release tags must match the release commit prefix', () => {
  const Tag = ParseReleaseTag('1.5.0-build.4f43abcd')

  AssertBuildTagMatchesRevision(Tag, '4f43abcd99999999999999999999999999999999')
  Assert.throws(
    () => AssertBuildTagMatchesRevision(Tag, 'ffffffff99999999999999999999999999999999'),
    /must end with the first 8/
  )
})

test('event policy allows push only for build tags', () => {
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-build.4f43abcd'), 'push', undefined)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', false)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', true)
  AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'workflow_dispatch', undefined)
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'push', undefined),
    /must publish from release or workflow_dispatch/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0-beta.1'), 'release', false),
    /must be published from a GitHub prerelease/
  )
  Assert.throws(
    () => AssertReleaseEventAllowed(ParseReleaseTag('1.5.0'), 'release', true),
    /must not be published from a GitHub prerelease/
  )
})

test('check mode accepts matching committed Cargo versions', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    releasePublish: false
  })

  Assert.deepEqual(Result, {
    mode: 'check',
    packageName: PackageName,
    version: '0.1.0'
  })
})

test('check mode rejects mismatched committed Cargo versions', TestContext => {
  const WorkspaceValue = CreateWorkspace('0.1.0', '0.2.0')
  TestContext.after(() => Cleanup(WorkspaceValue))

  Assert.throws(
    () => RunVersioning({
      workspacePath: WorkspaceValue.root,
      manifestPath: 'Cargo.toml',
      lockfilePath: 'Cargo.lock',
      packageName: PackageName,
      releasePublish: false
    }),
    /version must match/
  )
})

test('release mode rewrites Cargo versions and emits the image plan', TestContext => {
  const WorkspaceValue = CreateWorkspace()
  const ImagePlanOutput = Path.join(WorkspaceValue.root, 'image-plan.json')
  TestContext.after(() => Cleanup(WorkspaceValue))

  const Result = RunVersioning({
    workspacePath: WorkspaceValue.root,
    manifestPath: 'Cargo.toml',
    lockfilePath: 'Cargo.lock',
    packageName: PackageName,
    ref: 'refs/tags/1.5.0-beta.1',
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    eventName: 'release',
    releasePrerelease: true,
    releasePublish: true,
    imagePlanOutput: ImagePlanOutput
  })

  const Manifest = Fs.readFileSync(WorkspaceValue.manifestPath, 'utf8')
  const Lockfile = Fs.readFileSync(WorkspaceValue.lockfilePath, 'utf8')
  const Plan = JSON.parse(Fs.readFileSync(ImagePlanOutput, 'utf8')) as ReleasePlanSummary

  Assert.deepEqual(Result, {
    mode: 'release',
    packageName: PackageName,
    version: '1.5.0-beta.1'
  })
  Assert.match(Manifest, /^version = "1\.5\.0-beta\.1"$/m)
  Assert.match(Lockfile, /^version = "1\.5\.0-beta\.1"$/m)
  Assert.equal(Plan.image, 'ghcr.io/digitalbelt/sendmail-sec')
  Assert.equal(Plan.tag, '1.5.0-beta.1')
  Assert.equal(Plan.kind, 'beta')
})

test('stable image plan includes major aliases and stable manifest tags', () => {
  const Plan = BuildImageReleasePlan({
    releaseTag: ParseReleaseTag('5.2.0'),
    revision: 'aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',
    source: 'https://github.com/digitalBelt/sendmail-sec'
  })
  const Amd64 = Plan.artifacts.find(Artifact => Artifact.artifactArch === 'amd64')

  if (Amd64 === undefined) {
    throw new Error('stable image plan should include the amd64 artifact')
  }
  Assert.ok(Amd64.ghcrTags.includes('ghcr.io/digitalbelt/sendmail-sec:5-alpine-musl-amd64'))
  Assert.ok(Plan.manifests[0].ghcrTags.includes('ghcr.io/digitalbelt/sendmail-sec:latest'))
  Assert.ok(Plan.manifests[1].ghcrTags.includes('ghcr.io/digitalbelt/sendmail-sec:5-alpine-musl'))
})

test('beta and build image plans do not include latest or major aliases', () => {
  for (const Tag of ['5.2.0-beta.1', '5.2.0-build.4f43abcd']) {
    const Plan = BuildImageReleasePlan({
      releaseTag: ParseReleaseTag(Tag),
      revision: '4f43abcd99999999999999999999999999999999',
      source: 'https://github.com/digitalBelt/sendmail-sec'
    })
    const Serialized = JSON.stringify(Plan)

    Assert.equal(Serialized.includes(':latest'), false)
    Assert.equal(Serialized.includes(':5-alpine-musl'), false)
  }
})
